namespace SpriteKind {
    export const item = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f f 2 f e f . . 
        . . f f f 2 f e e 2 2 f f f . . 
        . . f e 2 f f e e 2 f e e f . . 
        . f f e f f e e e f e e e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . . e f f f f f f f f 4 e . . 
        . . . 4 f 2 2 2 2 2 e d d 4 . . 
        . . . e f f f f f f e e 4 . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e f 2 f f f 2 f 2 e f . . 
        . . f f f 2 2 e e f 2 f f f . . 
        . . f e e f 2 e e f f 2 e f . . 
        . f f e e e f e e e f f e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f e . . . 
        . . 4 d d e 2 2 2 2 2 f 4 . . . 
        . . . 4 e e f f f f f f e . . . 
        . . . . . . . . . f f f . . . . 
        `],
    100,
    true
    )
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile6`, function (sprite, location) {
    statusbar2 = statusbars.create(20, 4, StatusBarKind.EnemyHealth)
    mySprite2 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    statusbar2.setBarBorder(1, 1)
    statusbar2.attachToSprite(mySprite2)
    tiles.placeOnTile(mySprite2, tiles.getTileLocation(randint(1, 8), randint(1, 8)))
    mySprite2.follow(mySprite, 75)
    tiles.setTileAt(location, assets.tile`myTile8`)
    characterAnimations.loopFrames(
    mySprite2,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111df.......
        ......fd1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd1dfbddddbf......
        ......fbddfcdbbbcf......
        .......f11111bbcf.......
        .......f1b1fffff........
        .......fbfc111bf........
        ........ff1b1bff........
        .........fbfbfff.f......
        ..........ffffffff......
        ............fffff.......
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        .........fffff..........
        ........f11111ff........
        .......fb111111bf.......
        .......f1111111dbf......
        ......fd111111dddf......
        ......fd11111ddddf......
        ......fd11dddddddf......
        ......f111dddddddf......
        ......f11fcddddddf......
        .....fb1111bdddbf.......
        .....f1b1bdfcfff........
        .....fbfbffffffff.......
        ......fffffffffff.ff....
        ...........ffffffff.....
        ........f1b1bffffff.....
        ........fbfbffffff......
        ........................
        ........................
        ........................
        ........................
        `],
    100,
    characterAnimations.rule(Predicate.MovingLeft)
    )
    characterAnimations.loopFrames(
    mySprite2,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........fffff.........
        ........ff11111f........
        .......fb111111bf.......
        ......fbd1111111f.......
        ......fddd111111df......
        ......fdddd11111df......
        ......fddddddd11df......
        ......fddddddd111f......
        ......fddddddcf11f......
        .......fbdddb1111bf.....
        ........fffcfdb1b1f.....
        .......ffffffffbfbf.....
        ....ff.fffffffffff......
        .....ffffffff...........
        .....ffffffb1b1f........
        ......ffffffbfbf........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `],
    100,
    characterAnimations.rule(Predicate.MovingRight)
    )
    characterAnimations.loopFrames(
    mySprite2,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......f11111111f.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......f1d11dd11d1f......
        ......f1d111111d1f......
        .......f11111111f.......
        ......fffcd111dffff.....
        .....cfffc1f1fcfffff....
        ....ffffffffffffffff....
        ....ffffffffffffffff....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......f11111111f.......
        .......f11111111f.......
        ......f111111111df......
        ......f111111111df......
        ......f1111111dddf......
        ......f11111111d1f......
        ......f11111111d1f......
        .......f1111111ffff.....
        ......fffcdb1bcfffff....
        ....fffffcbfbfffffff....
        ....ffffffffffffffff....
        ....fffffffffff.........
        .........fffff..........
        ..........fff...........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......f11111111f.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......f1d11dd11d1f......
        ......f1d111111d1f......
        .......f11111111f.......
        ......fffcdb1bdffff.....
        ....fffffcbfbfffffff....
        ....ffffffffffffffff....
        ....ffffffffffffffff....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......f11111111f.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......f1d11dd11d1f......
        ......f1d111111d1f......
        .....ffff1111111f.......
        ....fffffcdb1bdfff......
        ....fffffcbfbfcfffcf....
        ....ffffffffffffffff....
        .........fffffffffff....
        ..........fffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    100,
    characterAnimations.rule(Predicate.MovingUp)
    )
    characterAnimations.loopFrames(
    mySprite2,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111ffff.....
        ......fffcdb1bc111cf....
        ....fc111cbfbf1b1b1f....
        ....f1b1b1ffffbfbfbf....
        ....fbfbfffffff.........
        .........fffff..........
        ..........fff...........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .....ffff111111bf.......
        ....fc111cdb1bdfff......
        ....f1b1bcbfbfc111cf....
        ....fbfbfbffff1b1b1f....
        .........fffffffbfbf....
        ..........fffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    100,
    characterAnimations.rule(Predicate.MovingDown)
    )
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    characterAnimations.clearCharacterState(mySprite)
    swordswing = 1
    animation.runImageAnimation(
    mySprite,
    [img`
        ..............................
        ..............................
        ..............................
        ..........ffff................
        ........fff22fff..............
        .......fff2222fff.............
        ......fffeeeeeefff............
        ......ffe222222eef............
        ......fe2ffffff2ef............
        ......ffffeeeeffff............
        .....ffefbf44fbfeff...........
        .....fee41fddf14eef...........
        ......ffffdddddeef............
        .....fddddf444eef.............
        .....fbbbbf2222f4e............
        .....fbbbbf2222fd4............
        ......fccf45544f44............
        .......ffffffff...............
        .........ff..ff...............
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..........ffff................
        ........fff22fff..............
        .......fff2222fff.............
        ......fffeeeeeefff............
        ......ffe222222eef............
        ......fe2ffffff2ef............
        ......ffffeeeeffff............
        .....ffefbf44fbfeff...........
        .....fee41fddf14eef...........
        ....fdfeeddddd4eff............
        ....fbffee444edd4e............
        ....fbf4f2222edde.............
        ....fcf.f22cccee..............
        .....ff.f44cdc4f..............
        ........fffddcff..............
        .........fddcff...............
        ........cddc..................
        ........cdc...................
        ........cc....................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        .........ffff.................
        .......fffffffe...............
        ......fffeefeefeeee..c........
        ......fffe2ff4e44ddecccccccc..
        .....ff22e2fb14ffddec1111111cc
        .....f222e2effd24fe.cccccccc..
        ....f2222e2e4dd25ff..c........
        ....f2222e2e4dd25ff...........
        .....f222e2effd24ff...........
        .....ff22e2fb1424ff...........
        ......fffe2ff4efff............
        ......fffeefeefe4.............
        .......ffffffffff.............
        ..........ffdbbcf.............
        ............ffff..............
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        `,img`
        ........c.....................
        ........c.....................
        .......c1c....................
        .......c1c....................
        .......c1c....................
        .......c1c....................
        .......c1c....................
        .......c1c....................
        ......cc1cc...................
        .......ccc....................
        .......ee.....................
        ......eddeffff................
        ......eddffffff...............
        ......e4f45544f4ff............
        ......e4f22222fefcf...........
        .....efe4dddd4effbf...........
        .....fe41fddf14efbf...........
        ....ffefbf44fbfefdf...........
        ....fffffeeeefffff............
        ....ffe22222222eff............
        ....ffeeeeeeeeeef.............
        .....fff222222fff.............
        .....fff222222fff.............
        ......fff2222fff..............
        ........ff22ff................
        ..........ff..................
        ..............................
        ..............................
        ..............................
        ..............................
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............ffff............
        .............fcbbdff..........
        .............ffffffffff.......
        .............4efeefeefff......
        ............fffe4ff2efff......
        ...........ff4241bf2e22ff.....
        ...........ff42dffe2e222f.....
        ...........ff52dd4e2e2222f....
        ........c..ff52dd4e2e2222f....
        ..cccccccc.ef42dffe2e222f.....
        cc1111111ceddff41bf2e22ff.....
        ..ccccccccedd44e4ff2efff......
        ........c..eeeefeefeefff......
        ...............efffffff.......
        .................ffff.........
        ..............................
        ..............................
        ..............................
        ..............................
        `,img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..................ff..........
        ................ff22ff........
        ..............fff2222fff......
        .............fff222222fff.....
        .............fff222222fff.....
        .............feeeeeeeeeeff....
        ............ffe22222222eff....
        ............fffffeeeefffff....
        ...........fdfefbf44fbfeff....
        ...........fbfe41fddf14ef.....
        ...........fbffe4dddd4efe.....
        ...........fcfef22222f4e......
        ............ff4f44554f4e......
        ...............ffffffdde......
        ................ffffedde......
        .....................ee.......
        ....................ccc.......
        ...................cc1cc......
        ....................c1c.......
        ....................c1c.......
        ....................c1c.......
        ....................c1c.......
        ....................c1c.......
        ....................c1c.......
        .....................c........
        .....................c........
        `],
    100,
    true
    )
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile15`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`myTile26`)
    mySprite3 = sprites.create(img`
        . . 2 2 b b b b b . . . . . . . 
        . 2 b 4 4 4 4 4 4 b . . . . . . 
        2 2 4 4 4 4 d d 4 4 b . . . . . 
        2 b 4 4 4 4 4 4 d 4 b . . . . . 
        2 b 4 4 4 4 4 4 4 d 4 b . . . . 
        2 b 4 4 4 4 4 4 4 4 4 b . . . . 
        2 b 4 4 4 4 4 4 4 4 4 e . . . . 
        2 2 b 4 4 4 4 4 4 4 b e . . . . 
        . 2 b b b 4 4 4 b b b e . . . . 
        . . e b b b b b b b e e . . . . 
        . . . e e b 4 4 b e e e b . . . 
        . . . . . e e e e e e b d b b . 
        . . . . . . . . . . . b 1 1 1 b 
        . . . . . . . . . . . c 1 d d b 
        . . . . . . . . . . . c 1 b c . 
        . . . . . . . . . . . . c c . . 
        `, SpriteKind.Food)
    tiles.placeOnTile(mySprite3, location)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.tileKindAt(TileDirection.Top, assets.tile`myTile21`)) {
        tiles.setTileAt(tiles.getTileLocation(2, 0), assets.tile`myTile24`)
        music.play(music.melodyPlayable(music.bigCrash), music.PlaybackMode.UntilDone)
        tiles.setTileAt(tiles.getTileLocation(5, 0), assets.tile`myTile3`)
        pause(100)
        tiles.setTileAt(tiles.getTileLocation(5, 0), assets.tile`myTile4`)
        pause(100)
        tiles.setTileAt(tiles.getTileLocation(5, 0), assets.tile`myTile5`)
        pause(100)
        tiles.setTileAt(tiles.getTileLocation(5, 0), assets.tile`myTile2`)
    }
    if (mySprite.tileKindAt(TileDirection.Top, sprites.dungeon.purpleSwitchUp)) {
        tiles.setTileAt(tiles.getTileLocation(6, 5), sprites.dungeon.purpleSwitchDown)
        music.play(music.melodyPlayable(music.bigCrash), music.PlaybackMode.UntilDone)
        tiles.setTileAt(tiles.getTileLocation(7, 5), assets.tile`myTile3`)
        pause(100)
        tiles.setTileAt(tiles.getTileLocation(7, 5), assets.tile`myTile4`)
        pause(100)
        tiles.setTileAt(tiles.getTileLocation(7, 5), assets.tile`myTile5`)
        pause(100)
        tiles.setTileAt(tiles.getTileLocation(7, 5), assets.tile`myTile2`)
    }
    if (mySprite.tileKindAt(TileDirection.Top, assets.tile`myTile2`)) {
        tiles.setCurrentTilemap(tilemap`level16`)
        filly = 1
        fillx = 1
        for (let index = 0; index < 100; index++) {
            if (Math.percentChance(80)) {
                tiles.setTileAt(tiles.getTileLocation(0 + filly, 0 + fillx), tileList._pickRandom())
                fillx += 1
                if (fillx == 9) {
                    fillx = 1
                    filly += 1
                }
                if (filly == 9) {
                    fillx = 1
                    filly += 1
                }
            } else if (Math.percentChance(20)) {
                tiles.setTileAt(tiles.getTileLocation(0 + filly, 0 + fillx), lucky_list._pickRandom())
                fillx += 1
                if (fillx == 9) {
                    fillx = 1
                    filly += 1
                }
            }
        }
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile7`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`myTile25`)
})
controller.down.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d e e e e e f . . . 
        . . . f e 4 e d d 4 f . . . . . 
        . . . f 2 2 e d d e f . . . . . 
        . . f f 5 5 f e e f f f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `,img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e d d 4 . . . . 
        . . . f 2 2 2 2 e d d e . . . . 
        . . f f 5 5 4 4 f e e f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `],
    100,
    true
    )
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile18`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`myTile30`)
    minion += 1
})
statusbars.onZero(StatusBarKind.EnemyHealth, function (status) {
    sprites.destroy(mySprite2)
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    info.changeLifeBy(-1)
    statusbar.value = 100
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e e e d d d f . . . 
        . . . . . f 4 d d e 4 e f . . . 
        . . . . . f e d d e 2 2 f . . . 
        . . . . f f f e e f 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `,img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . 4 d d e 4 4 4 e f . . . 
        . . . . e d d e 2 2 2 2 f . . . 
        . . . . f e e f 4 4 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `],
    100,
    true
    )
})
controller.up.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . . f e 4 d d d d 4 e f e . . 
        . . f e f 2 2 2 2 e d d 4 e . . 
        . . e 4 f 2 2 2 2 e d d e . . . 
        . . . . f 4 4 5 5 f e e . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . e f e 4 d d d d 4 e f . . . 
        . . e 4 d d e 2 2 2 2 f e f . . 
        . . . e d d e 2 2 2 2 f 4 e . . 
        . . . . e e f 5 5 4 4 f . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . . . . . f f f . . . . 
        `],
    100,
    true
    )
})
controller.B.onEvent(ControllerButtonEvent.Released, function () {
    timer.after(600, function () {
        swordswing = 0
        animation.stopAnimation(animation.AnimationTypes.All, mySprite)
    })
})
function generator () {
	
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    statusbar.value += 25
    sprites.destroy(otherSprite)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (swordswing == 1) {
        if (characterAnimations.matchesRule(mySprite2, characterAnimations.rule(Predicate.MovingUp))) {
            mySprite2.y += 10
        }
        if (characterAnimations.matchesRule(mySprite2, characterAnimations.rule(Predicate.MovingDown))) {
            mySprite2.y += -10
        }
        if (characterAnimations.matchesRule(mySprite2, characterAnimations.rule(Predicate.MovingRight))) {
            mySprite2.x += -10
        }
        if (characterAnimations.matchesRule(mySprite2, characterAnimations.rule(Predicate.MovingLeft))) {
            mySprite2.x += 10
        }
        statusbar2.value += -50
    } else {
        scene.cameraShake(4, 100)
        animation.runImageAnimation(
        mySprite,
        [img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .....fffc1111111f.......
            ...fc111cd1111111f......
            ...f1b1b1b1111dddf......
            ...fbfbffcf11fcddf......
            ......fcf111111bbf......
            .......ccbdb1b1fcf......
            .......fffbfbfdff.......
            ........ffffffff........
            ........fffffffffff.....
            .........fffffc111cf....
            .........fffff1b1b1f....
            ..........ffffbfbfbf....
            ...........ffff.........
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ....7.fd11111111df......
            ...7..fd11111111df......
            ...7..fd11111111df......
            ...7..fddd1111dddff.....
            ...77.fbdbfddfbdbfcf....
            ...777fcdcf11fcdcfbf....
            ....77fffbdb1bdffcf.....
            ....fcb1bcffffff........
            ....f1c1c1ffffff........
            ....fdfdfdfffff.........
            .....f.f.f..............
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd111111111f......
            ......fd11111111df......
            ......fd11111111df......
            ......fcdd1111ddcff.....
            .......fbcf11fcbfbbf....
            .......ffbdb1bdffff.....
            ........fcbfbfdf........
            ........ffffffff........
            ......ffffffffff........
            .....fcb1bcffff.........
            ......ffbff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fdd111111ddf......
            ......fbdd1111dddf......
            ......fcdbfddfbdbf......
            .......fbcf11fcbfff.....
            .......ffb1111bcfbcf....
            ........fcdb1bdfbbbf....
            .......ffffffffffcf.....
            .....fcb1bcfffff........
            .....f1b1b1ffff.........
            ......ffbff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . 2 2 2 2 . . . . . . 
            . . . . 2 2 2 2 2 2 2 2 . . . . 
            . . . 2 2 2 2 2 2 2 2 2 2 . . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
            . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . . 2 2 2 2 2 2 2 2 2 2 . . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . . . . 2 2 2 2 2 2 . . . . . 
            . . . . . 2 2 . . 2 2 . . . . . 
            `,img`
            . . . . . . 2 2 2 2 . . . . . . 
            . . . . f f 2 2 2 2 2 2 . . . . 
            . . . f f f 2 2 2 2 2 2 2 . . . 
            . . f f f e 2 2 2 2 2 2 2 2 . . 
            . . f f e 2 2 2 2 2 2 2 2 2 . . 
            . . f e 2 f 2 2 2 2 2 2 2 2 . . 
            . . f f f f 2 2 2 2 2 2 2 2 . . 
            . f f e f b 2 2 2 2 2 2 2 2 2 . 
            . f e e 4 1 2 2 2 2 2 2 2 2 2 . 
            . . f e e d 2 2 2 2 2 2 2 2 . . 
            . . . f e e 2 2 2 2 2 2 2 . . . 
            . . e 4 f 2 2 2 2 2 2 2 2 2 . . 
            . . 4 d f 2 2 2 2 2 2 2 2 2 . . 
            . . 4 4 f 4 2 2 2 2 2 2 2 2 . . 
            . . . . . f 2 2 2 2 2 . . . . . 
            . . . . . f 2 . . 2 2 . . . . . 
            `,img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 2 2 2 . . . . 
            . . . f f f 2 2 2 2 2 2 2 . . . 
            . . f f f e e e e 2 2 2 2 2 . . 
            . . f f e 2 2 2 2 2 2 2 2 2 . . 
            . . f e 2 f f f f 2 2 2 2 2 . . 
            . . f f f f e e e 2 2 2 2 2 . . 
            . f f e f b f 4 4 2 2 2 2 2 2 . 
            . f e e 4 1 f d d 2 2 2 2 2 2 . 
            . . f e e d d d d 2 2 2 2 2 . . 
            . . . f e e 4 4 4 2 2 2 2 . . . 
            . . e 4 f 2 2 2 2 2 2 2 2 2 . . 
            . . 4 d f 2 2 2 2 2 2 2 2 2 . . 
            . . 4 4 f 4 4 5 5 2 2 2 2 2 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `],
        100,
        false
        )
        sprites.destroy(statusbar2)
        sprites.destroy(otherSprite)
        statusbar.value += -25
    }
})
let minion = 0
let fillx = 0
let filly = 0
let mySprite3: Sprite = null
let swordswing = 0
let mySprite2: Sprite = null
let statusbar2: StatusBarSprite = null
let mySprite: Sprite = null
let tileList: Image[] = []
let lucky_list: Image[] = []
let statusbar: StatusBarSprite = null
info.setLife(3)
statusbar = statusbars.create(20, 4, StatusBarKind.Health)
// Reference to tile kind `myTile8`
// Reference to tile kind `myTile9`
// Reference to tile kind `myTile12`
// Reference to tile kind `myTile14`
// Reference to tile kind `myTile11`
// Duplicate is fine if you want more chances for this tile
// Reference to tile kind `myTile7`
// Reference to tile kind `myTile6`
// Reference to tile kind `myTile10`
// Duplicate `myTile8`
lucky_list = [
assets.tile`myTile8`,
assets.tile`myTile9`,
assets.tile`myTile12`,
assets.tile`myTile8`,
assets.tile`myTile11`,
assets.tile`myTile14`,
assets.tile`myTile18`,
assets.tile`myTile8`,
assets.tile`myTile20`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`
]
// Reference to tile kind `myTile8`
// Reference to tile kind `myTile9`
// Reference to tile kind `myTile12`
// Reference to tile kind `myTile14`
// Reference to tile kind `myTile11`
// Duplicate is fine if you want more chances for this tile
// Reference to tile kind `myTile7`
// Reference to tile kind `myTile6`
// Reference to tile kind `myTile10`
// Duplicate `myTile8`
tileList = [
assets.tile`myTile8`,
assets.tile`myTile9`,
assets.tile`myTile12`,
assets.tile`myTile14`,
assets.tile`myTile11`,
assets.tile`myTile14`,
assets.tile`myTile8`,
assets.tile`myTile6`,
assets.tile`myTile10`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile15`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile7`,
assets.tile`myTile7`,
assets.tile`myTile7`,
assets.tile`myTile6`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`,
assets.tile`myTile8`
]
tiles.setCurrentTilemap(tilemap`level6`)
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
statusbar.attachToSprite(mySprite)
statusbar.value = 100
statusbar.setBarBorder(1, 15)
tiles.placeOnTile(mySprite, tiles.getTileLocation(7, 7))
scene.cameraFollowSprite(mySprite)
game.onUpdate(function () {
	
})
forever(function () {
	
})
